# GENERATED by update-fedora-deps.py -- do not hand-edit.
# Bump with: make update-fedora-deps FCOS=<version> [SYSTEMD=<nvr>]
# Kernel from Fedora CoreOS; systemd-boot stub from Fedora 44. All RPMs are
# GPG-verified against keys/RPM-GPG-KEY-fedora-44-primary at bump time and every build.

FEDORA_RELEASE := 44
FEDORA_KERNEL_VERSION := 7.0.12-201.fc44
FEDORA_KERNEL_BASE_URL := https://kojipkgs.fedoraproject.org/packages/kernel/7.0.12/201.fc44/data/signed/6d9f90a6
SYSTEMD_BOOT_VERSION := 259.6-1.fc44
SYSTEMD_BOOT_BASE_URL := https://kojipkgs.fedoraproject.org/packages/systemd/259.6/1.fc44/data/signed/6d9f90a6

FEDORA_KERNEL_CORE_SHA256_x86_64 := 5c549be1c1157dd58693344777cc7722e8c13350b6fcc96cacf72cd64d52f358
FEDORA_KERNEL_CORE_SHA256_aarch64 := ccbd289e27706d00a6587360f7cf6a3c5742bd124ebe7c511b98a2ca9e73fe8c
FEDORA_KERNEL_MODULES_SHA256_x86_64 := f9f000cbc1ba3b49c2cbd105cc1ccc10d2d9f9e10802e92d6c966c8d1375857c
FEDORA_KERNEL_MODULES_SHA256_aarch64 := f282c61f947a9dee282b66b89b528876b1e4d9be505f15133811953419fefa28
SYSTEMD_BOOT_SHA256_x86_64 := 6a3707da87640b2fca178e5c7e44cf92fa6321f3389c166f713b4f9b0411ff20
SYSTEMD_BOOT_SHA256_aarch64 := 190a2559e97d381d2de3be786d55b359df1c0b4067427c025ef31ce4177e0d2a
